language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "pip install poetry"
  - "poetry install -v"
script:
  - "poetry run flake8 example/"
  - "poetry run flake8 tests/"
  - "poetry run pytest"
